<?php

function week8p1_menu() {
    $items = array();
    $items['week8p1'] = array(
        'title' => 'This is SI 635 Week 8 Part 1 Homework!',
        'page callback' => 'week8p1_hello',
        'access callback' => True,
    );
    return $items;
}


function week8p1_hello() {
    drupal_set_message(t('An error occurred and processing did not complete.'), 'error');
    // provides debug info to the user
    return l(t("Click here to be rerouted"),'node/1');
}
