<?php

function week8p3_menu() {
    $items = array();
    $items['week8p3'] = array(
        'title' => 'week8p3',
        'page callback' => 'week8p3_hello',
        'access callback' => true,
    );
    return $items;
}


function week8p3_hello() {
    drupal_goto("node/25");
    // drupal_goto takes the user to a different site; its a redirect
    return t("Hooray you have arrived at Node 25! Congratulations!");
}
